In [2]:
import pandas as pd
import numpy as np
import os

### Question 1

What version of Pandas are you running?

In [4]:
print(pd.__version__)

3.0.6

### Question 2

How many records are in the dataset?

In [6]:
# Import data
path = os.getcwd() # Get current folder
df = pd.DataFrame(
    data=pd.read_csv(path + '/car_fuel_efficiency_2026.csv')
)
print(len(df))

10000

### Question 3

How many different fuel types are there in the dataset?

In [8]:
df['fuel_type'].value_counts() # Just count the categories

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

### Question 4

How many columns in the dataset have missing values?

In [9]:
# Just count the columns with null values from info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

### Question 5

What is the max fuel efficiency of cars from Asia?

In [11]:
# Group the datatable by origin and calculate the max fuel efficiency of each one
df.groupby('origin')[['fuel_efficiency_mpg']].max()

        fuel_efficiency_mpg
origin
Asia                   41.2
Europe                 39.4
USA                    38.2

### Question 6

1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

In [20]:
# Find median horsepower
med = df['horsepower'].median()
mode = df['horsepower'].mode()[0]
print(f'Median before replacement: {med}')

rep_df = df.fillna({'horsepower': mode})
rep_df_med = rep_df['horsepower'].median()
print(f'Median after replacement: {rep_df_med}')

Median before replacement: 254.0
Median after replacement: 252.0

### Question 7

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [24]:
# Subset df
asia_df = df[df['origin'] == 'Asia'].reset_index()
asia_df = asia_df[['vehicle_weight', 'model_year']][:7]
asia_df

   vehicle_weight  model_year
0            4240        1996
1            4310        1992
2            4230        1997
3            4420        1978
4            3950        2007
5            4750        2021
6            4450        2019

In [34]:
# Get table as array
X = asia_df.to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [51]:
# X * X.T
XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [52]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [55]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
x = XTX_inv.dot(X.T)
w = x.dot(y)
w.sum()

0.3691969690492649